### PR TITLE
Result tab on the team page

### LINKED ISSUE #64: [Team page] Populate the result tab
Add a "Résultats" tab in the team's page with a list view in its body. This list view contains:
  - An item per competition (Championnat, Challenge, Coupe de printemps)
  - Each item will display the ranking of the team (same graph as the dashboard one)
  - The type of competition must also be displayed (4x4 mixte, 6x6 masculin, ...). Use a graphic instead of text
  - Each item must provide a "détails" text (at the right bottom?). When the user clicks on this text then a sub container must be opened (with a smooth animation) which will display the matches results (date of the match, the competitor's name, the final score, the detailed scores of each set)

### PR DESCRIPTION
**Pull request by thomasFoulon**
Close #64 

A first job on the result tab. For the moment, we can-t click on a result card to see more information.

What do you think of the design ?

### CODE REVIEW

**Comment by eric-taix-teads** [comment]
A general question not only to this PR: do we want or not add some elevation for cards. Some cards in the application have an elevation other don't have! I remember that I removed the elevation because of an issue in the club list page, and I found that "flat" cards look well but we can change it: the most important is that every clickable cards must have the same design.

On your design:
- I think that the vertical bar (between the score and the labels) should not use the same color as the labels: something more lighter
- is the date of entry (of a match) is really important? do you have the date of the match? I think that this one is much more relevant
- I love the color which changes according if the team won or lost
- for the opponents I would have used a centered text, and one line per team (plus a line for `vs` with a smaller font size)
```
LVB / Les commandos  
       vs
   Clapiers 2
```

**Comment by thomasFoulon** [comment]
I think that an elevation looks well and emphasize the card. Actually on the dashboard, I think it would be nice to have an elevation. Moreover, I think that it's not evident that cards are clickable on the dashboard.

I thought about different solutions like a little text with an arrow at the bottom-right of the card which says "Cliquez pour plus de détails >" or "Détails >".
Another solution could be to just add an arrow ">" on the right of the card.

**Comment by eric-taix-teads** [comment]
I agree with you about the elevation. And the right arrow in the title of the card seems also a very good idea.
For this PR I've forgotten to mention that all cards, titles, app bar, bottom bar have a rounded corner. Your result cards seem to have a rectangular corner or a too small rounded corner no ?

**Comment by thomasFoulon** [comment]
I think that for these cards a lower radius for the corner is better because they are a lot of them, that's like a list. What do you think ?

In the details of the match I'm going to use cards with the normal radius.

**Comment by eric-taix** [comment]
Yes but we also have the club list with rounded corners and in the agenda
too!
Perhaps you can try a radius between the one you used and the one used in
the club list. But for the consistency of the UI, I think we must have the
same corner radius in all list (no matter the radius value: small or big or
medium).

Le ven. 17 juil. 2020 à 12:22, thomasFoulon <notifications@github.com> a
écrit :

**Comment by thomasFoulon** [comment]
I agree ! Maybe a little radius then.

**Comment by thomasFoulon** [comment]
Here is my proposition for more information on a match when you click on a result card. What do you think ?

**Comment by eric-taix-teads** [comment]
Other thoughts: 

  1. I'm not sure that repeating the names of the teams for each set is interesting and even I find it counterproductive (We already know the names of the teams)!
Did you imagine/try to use a listview like:  
```
set 1           20-25
set 2           25-12
```  
  2. Definitively I would have remove all cards in this page (with or without elevation)
  3. Could we put a sentence to give the score ? (not in a card)  
```
VCV/Les diablotins perd
                    2-3
          contre AV2M/LEs Chewbacca  
```
  The first team is the host, the second team is the visitor. The first team is left aligned, the second is right aligned.
  4. I think it could be cool to add the logo of the club on the left/right (first/second team)  
  5. I think that colors could better reflect the result (visually) if we set the color per point: use green for 25 and red for the opposite. Same for the final result. Then if you won 3-2, you will have 3 green sets and 2 red sets in the details panel.

**Comment by thomasFoulon** [comment]
I've taken into account your comments. Here is the result.

What do you think ?

**Comment by Lo0ping** [comment]
image
Here my initial page design

**Comment by eric-taix** [comment]
Alignements are weird ! Especially for sets. Try to right align the first
column.
You can also try to replace the red color to white.
Also I think that the font is too bold.
Add the logo of the club.
I think that the final result as the first displayed information is a good
thing. But perhaps you could try:

      Asvmt3
         gagné/perd contre
     Les diablotins

         3-2
(Sorry I'm on my phone so it's difficult to explain but as Laurent did is
centered)

**Comment by thomasFoulon** [comment]
I'll try to realize Laurent's page design.

**Comment by thomasFoulon** [comment]
Fetching the logo of the opponent club every time a user clicks to see details on a match will be heavy. How can I do ?

**Comment by thomasFoulon** [comment]
Here is the result. What do you think ?

For the moment, until issue #78 is not resolved, a placeholder is used for the opponent team club logo.

**Comment by eric-taix-teads** [comment]
Comestic comments:
  - There are a lot of spacing between the final score the visitor
  - Personally I don't understand the color of the final result, perhaps just try to set the color to white or set only the color of the team you come from
  - The placeholder shape should be circle no? Currently it's oval

**Comment by eric-taix-teads** [comment]
And as mentionned in a previous comment, if you add the "gagne"/"perd"/"contre" in the same line as the names of teams it could be too long. Did you try my proposal: https://github.com/eric-taix/volley34-mobile/pull/76#issuecomment-660638887

**Comment by thomasFoulon** [comment]
The placeholder is oval because the image I used is rectangle and then it doesn't render well.

**Comment by thomasFoulon** [comment]
The color was here to indicate if this is a victory or a defeat.

**Comment by thomasFoulon** [comment]
This is what you want ? :smile:

**Comment by eric-taix-teads** [comment]
Much better 👍  Can you set the font of "gagne contre"/"perd contre" in `NORMAL` instead of `BOLD` ? It will help to better understand which teams are involved in this match and reduce the font size a little if possible

**Pull request merged**
