### PR TITLE
Click on agenda other agenda items

### LINKED ISSUE #107: [agenda dashboard] Make events which are not matches clickable
For now only match events are clickable on the dashboard agenda. The next step is to make other events clickable to see more details about them (same details as matches and same interaction).

### PR DESCRIPTION
**Pull request by thomasFoulon**
Close #107 

Other agenda items than matches are now clickable.

### CODE REVIEW

**Comment by eric-taix** [comment]
I would have organise these kind of pages with an icon on the left like .

I know that some tournament have an image which is sent to @Lo0ping . If there are no image right now you can mimic by hard coded one in your model (but remove it before commit - is just for test purpose). I don't know how did you implement it but you could try to set the image in the background of the app bar which fades out when the user scroll (just an idea which provides a nice effect).

**Comment by Lo0ping** [comment]
Hello,

This page is fine but it miss event poster that it can provided

**Comment by eric-taix-teads** [comment]
FTR and how you could implement a collapsing image with sliver appbar see https://medium.com/@diegoveloper/flutter-collapsing-toolbar-sliver-app-bar-14b858e87abe
If the image is not provided you could then use the default color for appbar

**Comment by thomasFoulon** [comment]
Here is the result. It works like in the medium.com article. (The first image is a test with a sample image but the final is like the other ones  result hasn't any image because it's not provided).

**Comment by eric-taix** [comment]
Can you align values left instead of center?
Split date & hour in 2 lines with a clock as icon for hours
For date use the format "Dimanche 13 septembre" (without year and month word)
The location icon is not the proper one. Use the same icon as the one in the tab
Why did you add a tab? Adding the map in the location line would be much better.
For actions I think it's much better in this case to use buttons with label and to put them under the values (not at the end of line). Note: don't use default action buttons here, there's no default action

**Comment by eric-taix-teads** [comment]
👍 
The `Informations` is not required right now as this is the only tab. It can be added when the `Statistiques` tab will be added but it does not matter if you keep it for now. 

The last thing which disturbs me: this is the only tab which has an icon! I don't think that it is valuable to add this icon: the label is well understandable

**Comment by thomasFoulon** [comment]
Note that we can't provide a map for events which are not matches because GPS coordinates are not provided for places which are not gymnasiums.

**Review by eric-taix-teads — APPROVED** [review]
LGTM 👍 

> Note that we can't provide a map for events which are not matches because GPS coordinates are not provided for places which are not gymnasiums.

Perhaps coordinates exist in the database and @Lo0ping can add them in the response for other events ?

**Comment by Lo0ping** [comment]
CalendarEvent Place is a single Text Field even if it's a gymnasium

image

**Comment by Lo0ping** [comment]
I don't like this 

image

please revert here : 

image

but without place panel

**Comment by thomasFoulon** [comment]
You want me to set a sample image isn't it ? When the user scrolls down, the image disappear to look like your first screenshot !

**Comment by thomasFoulon** [comment]
For matches events we don't fetch the CalendarEvent with `/calendars`. In reality we use `/matchs` in the API. That's why we have the GPS coordinates thanks to the `CodeGymnase` entry ! We can't do that for other events than matches...

**Comment by thomasFoulon** [comment]
I merge the branch and I'll change it if it's necessary.

**Pull request merged**
