### PR TITLE
Ranking tabs on the team page

### LINKED ISSUE #77: [team page] Populate the ranking tab
Add a "Classement" tab in the team's page with a list view in its body which will contain graphs and data on the ranking in competitions.

### PR DESCRIPTION
**Pull request by thomasFoulon**
Close #77 

I created the ranking tabs on the team page.

The ranking page contains :
- the ranking in the competition (first, fourth, etc),
- the number of matches, sets and points won compared to the total,
- the number of matches of each score.

Ranking

### CODE REVIEW

**Comment by eric-taix-teads** [comment]
Some design guidelines:
  - cards are reserved when you can click to display details
  - don't set elevation for cards: use the default set in the theme (if we want to use an elevation it will be easier)
  - use main colors (i.e. white for dark theme) only for useful informations (and use lighter/darker colors for useless sentence)
  - I persist and think that the last graphic/data (sets distribution) can be much better

**Comment by thomasFoulon** [comment]
Here is the result !

ranking tab result 2

**Comment by Lo0ping** [comment]
Hi,
Don't forget that you can have unfinished match with score : 0-1, 1-0, 1-1, 1-2, 2-1, 2-2

**Comment by thomasFoulon** [comment]
@Lo0ping Where can I find this information ? Is it on what is returned by http://api.volley34.fr/v1/classements/equipes/CVBF2 ?

**Comment by eric-taix** [comment]
Perhaps <NbSets_MI>1</NbSets_MI> ?
I think we must only display one value for all unfinished matches otherwise
we will have too much values and it will make noise. Also it should only be
a few percentage of matches that don't finish

Le mer. 29 juil. 2020 à 11:07, thomasFoulon <notifications@github.com> a
écrit :

**Comment by thomasFoulon** [comment]
What can I write for not finished matches which is not too long then ?

**Comment by eric-taix-teads** [comment]
I don't like the pie chart: it's a bit a 90's chart. Why don't you use the distribution graph used in the team's statistics? Its design is more actual, even if a team never won a match 3-0 then you'll see it, each value has always the same place (so easier to read) which is not the case for the pie chart and it's easier to compare how the team perform.

I tried to manually design the UI of this page:


The numbers beside each graph are the order to display them (from the most important to the details)

The second graph in "Sets gagnés" is the evolution of the won sets vs lost sets (the same graph used in club' teams page)

As you see I've not more used the full circle graph: I'm not happy with it. We'll only use the partial circle from now.

**Comment by thomasFoulon** [comment]
I can do it but I don't like vertical writing, it's not convenient for the user. I can propose you a compromise !

**Comment by thomasFoulon** [comment]
I can I know if a team is promoted or relegated ?

**Comment by eric-taix-teads** [comment]
> I can do it but I don't like vertical writing, it's not convenient for the user. I can propose you a compromise !

Yes you already said it to me ;-) Ok you can try with horizontal writing and let's see . But my proposal was to make a (big) difference between a section's title and a legend. This is not really to be read but just add a tip about the data displayed.

> How can I know if a team is promoted or relegated ?

For each competition you receive the number of relegated and promoted teams (i.e. in http://api.volley34.fr/v1/classements/equipes/CVBF2 this is `Relegue ` and `Promu` fields). If a team's classification is 2nd and the number of promoted is 3, then this team will be promoted. If a team's classification is 3rd from the end and the number a relegated is 2, then this team will not be relegated.

`classification of team <= Promu` => promoted
`number of team - classification of team <= Relegue` => relegated

**Comment by eric-taix-teads** [comment]
> What can I write in the pie chart for not finished matches which is not too long then ?

Don't have a clear idea for now.
  - `NT`
  - `Autres`
  - `?`
  - `-`
  - `...`

`Autres` could be the best wording, but I'm afraid it's a bit long compared to `3-0`, `3-1`, ...

Otherwise we can "change" the score by adding 1 or more sets to each team until one of two reach 3? Because even if the match is not finished, there's always a winner (determined by the team which has the higher number of sets and if there's an equality then the number of points). So if a team win `2-1` then in the sets distribution graph, the important thing is that there's only one set of difference. if we put this result in the `3-2` distribution, I think it's acceptable.
If a team win `2-2` using the points, then it's also acceptable to say that this team win `3-2`.

And if I remember well even if a team win `2-2` using points to decide between them, it will have 3 points

**Comment by thomasFoulon** [comment]
Here is the result. This is a newer version than the last pushed commit but I don't push it to avoid a potential useless commit (codemagic limited time of build) in the case of modification requirement. What do you think ?

ranking tab result 3

**Comment by eric-taix-teads** [comment]
Can you just do some screenshots ? It's difficult to have a look to the
details with an animation

**Comment by eric-taix-teads** [comment]
- Avoid bold for labels (i.e. "Matchs gagnés", ... and "3-0", "3-1")
- Add some vertical padding between each graph
- "Résultats de vos matchs" is also a statistic so you don't need a paragraph
- The order of statistics is not correct:
  - "Matchs gagnés"
  - "Scores" (sets distributions)
  - "Sets gagnés"
  - "Différence de sets" (you missed this graph)
  - "Points gagnés"
- The height of the distribution of sets is too important you can reduce it (like the one in the team's details)
- You can align the label of each statistic (try left and right, I'm not sure which one will be the best option)
- if you consider each statistic, there are 3 columns: label + optional text + graphic. For the sets distribution, the graph should take the last two columns width
- same for the missed graph ("Différence de sets")
- in my manuel design, you probably don't understand what I meant for "4x4 mixte - Nv Excellence". This is a text between the tabs and the first paragraph. It indicates the type of competition and the level of the team.
- the title of the first paragraph is just "Classement" (we don't need the year, nor the name of the competition which is already in the tab, nor the type of competition/level as it should be displayed in the text before the first tab) and the font/size should be the font and size of the paragraph "Statistiques"
- instead of the text "4x4 mixte" you can use a widget, I've started to create: `CompetitionBadge`. It is not yet finished but can be a good starting point if you want to use it. My goal was to draw a badge with 2 parts. Each part can have 2 colors (pink or blue) in the background and can have a number. If the badge is `4(b)/4(b)` then it is a 4x4 male competition, if it is `6(p)/6(b)` then this is 6x6 mixed competition (colors are expressed with `(color)` with `b`=blue and `p`=pink)

Otherwise start to be good for me 👏

**Comment by eric-taix-teads** [comment]
And forgot to mention, that the number in the sets distribution would probably be better if you put them in the graph instead of at the bottom: it's confusing to see `1-3` and to see `1` under this text. The role of the abscissa is to set the title for each value but not the value itself.

**Comment by thomasFoulon** [comment]
> The order of statistics is not correct

I think it's not a good idea to mix different types of graph (here the `ArcGraph` and the `BarChart`).

> The height of the distribution of sets is too important

It's the height of total played matches. If you add up each colored bar, you'll see that it makes the full height of a bar. I think it's maybe more logical because we well see the proportion.

>  It indicates the type of competition and the level of the team

Where can I find this information ?

**Comment by thomasFoulon** [comment]
> And forgot to mention, that the number in the sets distribution would probably be better if you put them in the graph instead of at the bottom: it's confusing to see `1-3` and to see `1` under this text. The role of the abscissa is to set the title for each value but not the value itself.

I don't know if it's possible directly with the provide widget, I'll see !

**Comment by Lo0ping** [comment]
> @Lo0ping Where can I find this information ? Is it on what is returned by http://api.volley34.fr/v1/classements/equipes/CVBF2 ? Is it `NbSets_MI` ?

yes

**Comment by eric-taix-teads** [comment]
> It's the height of total played matches. If you add up each colored bar, you'll see that it makes the full height of a bar. I think it's maybe more logical because we well see the proportion.
It does not mean that you can't reduce the height of this chart no? It was the same for the team's details and the graph is smaller!

> I don't know if it's possible directly with the provided widget, I'll see !
Yes it's possible, see https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/bar_chart/samples/bar_chart_sample3.dart

> I think it's not a good idea to mix different types of graph (here the ArcGraph and the BarChart). Maybe it's better to separate them.
Does it mean that you will group all graph with the same type even if it's not relevant? I understand your point of view but here you've created a virtual paragraph just to ungroup these graphs and this paragraph is useless as the sets distribution is a statistic too. And remember that what's it's important is to display first the most important/general information (i.e. the classification) and to display statistics more and more precise as you scroll.

**Comment by eric-taix-teads** [comment]
If you see that it's not very visual to mix different type of charts, a general pattern to mix alignement:
- the first graph is on the right
- the second on the left
- the third on the right
- ...

**Comment by thomasFoulon** [comment]
> It does not mean that you can't reduce the height of this chart no? It was the same for the team's details and the graph is smaller!

You're right, actually it was not what I wanted to express. I think that there is a minimum size for colored bars. If I reduce the height too much, we'll not see the difference between for example one match won at 3-0 and two matches won at 3-1.

**Comment by thomasFoulon** [comment]
> If you see that it's not very visual to mix different type of charts, a general pattern is to mix alignement

I'll try !

**Comment by thomasFoulon** [comment]
Here is the result !

**Comment by eric-taix-teads** [comment]
❤️❤️❤️
You were right: both sets evolution graphics are useful. 
We are not far from being able to merge it! 

I have no idea but "Evolution de la différence de sets" and "Evolution de la difference de sets cumulée" is too long. Perhaps something like "Ev. diff sets" and "Ev. diff sets cumulés" could be enough, WDYT?

These labels (and others) don't have to right font color: use a darker color for dark theme and a lighter color for light theme. Also the font size seems too big for a label. Can you try the same font size and color as the one I used in the team's statistics in the club page (t

**Comment by eric-taix-teads** [comment]
Looking forward to how users are going to like this page !

**Comment by thomasFoulon** [comment]
The result ! (Personally I prefer previous label colors, here we can't see them well...)

**Comment by eric-taix** [comment]
The previous was more visible. But these are labels not data !

The font size of "Classement" and "Statistiques" are different : use the
same font size and color of Paragraph widget.

You don't need to display the competition type on the same line

Le ven. 31 juil. 2020 à 18:42, thomasFoulon <notifications@github.com> a
écrit :

**Comment by eric-taix** [comment]
There is an issue in the last screenshot: the team won 4/8 matches but
there are only 4 results (score) in the graph

**Comment by thomasFoulon** [comment]
> There is an issue in the last screenshot: the team won 4/8 matches but there are only 4 results (score) in the graph

I'm pretty sure this is an incoherence on the API. Dates have been shifted so this is probably why...

**Comment by eric-taix** [comment]
You are probably right!
LGTM let's me it and deploy :+1

Le ven. 31 juil. 2020 à 19:09, thomasFoulon <notifications@github.com> a
écrit :

**Pull request merged**
